title:               新生代
url:                 https://xsdai.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              小新
  email:             xinsheng.dai@yandex.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
